language: r
r:
  - 3.4.2

install: Rscript install_travis.R
script: PRODUCTION_SLACK_AUTH_TOKEN=xyz-s PRODUCTION_SLACK_BOT_TOKEN=abc-d R CMD check automatedpremium --no-manual

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libssl-dev
