install.packages("httr", repos = "http://cran.us.r-project.org")
install.packages("httptest", repos = "http://cran.us.r-project.org")
install.packages("jsonlite", repos = "http://cran.us.r-project.org")
install.packages("anytime", repos = "http://cran.us.r-project.org")
install.packages("slackr", repos = "http://cran.us.r-project.org")
install.packages("caTools", repos = "http://cran.us.r-project.org")
install.packages("DMwR", repos = "http://cran.us.r-project.org")
install.packages("ROCR", repos = "http://cran.us.r-project.org")
install.packages("gbm", repos = "http://cran.us.r-project.org")
install.packages("automatedpremium", repos = NULL, type="source")
install.packages("devtools", repos="http://cran.us.r-project.org")
