install.packages("httr", repos = "http://cran.us.r-project.org")
stopifnot("httr" %in% installed.packages()[,'Package'])
install.packages("httptest", repos = "http://cran.us.r-project.org")
stopifnot("httptest" %in% installed.packages()[,'Package'])
install.packages("jsonlite", repos = "http://cran.us.r-project.org")
stopifnot("jsonlite" %in% installed.packages()[,'Package'])
install.packages("anytime", repos = "http://cran.us.r-project.org")
stopifnot("anytime" %in% installed.packages()[,'Package'])
install.packages("slackr", repos = "http://cran.us.r-project.org")
stopifnot("slackr" %in% installed.packages()[,'Package'])
install.packages("caTools", repos = "http://cran.us.r-project.org")
stopifnot("caTools" %in% installed.packages()[,'Package'])
install.packages("DMwR", repos = "http://cran.us.r-project.org")
stopifnot("DMwR" %in% installed.packages()[,'Package'])
install.packages("ROCR", repos = "http://cran.us.r-project.org")
stopifnot("ROCR" %in% installed.packages()[,'Package'])
install.packages("gbm", repos = "http://cran.us.r-project.org")
stopifnot("gbm" %in% installed.packages()[,'Package'])
install.packages("automatedpremium", repos = NULL, type="source")
stopifnot("automatedpremium" %in% installed.packages()[,'Package'])
install.packages("devtools", repos="http://cran.us.r-project.org")
stopifnot("devtools" %in% installed.packages()[,'Package'])
