install.packages("httr", repos = "http://cran.us.r-project.org")
install.packages("httptest", repos = "http://cran.us.r-project.org")
install.packages("jsonlite", repos = "http://cran.us.r-project.org")
install.packages("anytime", repos = "http://cran.us.r-project.org")
install.packages("slackr", repos = "http://cran.us.r-project.org")